"""rename department

Revision ID: 8ad5ffb538a2
Revises: 82a6173ca0a8
Create Date: 2024-07-02 07:27:48.980748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad5ffb538a2'
down_revision = '82a6173ca0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
